### ISSUE TITLE
Example publishes but when gztopic echo, nothing seems to be published

### ISSUE THREAD

**Issue by RDaneelOlivav** [jpieper/pygazebo#18]
Hi,

I'm executing the example of use in given where you publish in "/gazebo/default/model/joint_cmd".
It connects because when launched gzserver, if we do gztopic list , that topic gets listed. But when echoing that topic, there is nothing to be seen.
Does someone know what's happening?

**Comment by jpieper** [comment]
What version of pygazeo and gazebo are you using?

**Comment by RDaneelOlivav** [comment]
3.0.0, installed by easy_install. Any clues?

Enviado desde mi iPhone

**Comment by RDaneelOlivav** [comment]
/usr/local/lib/python2.7/dist-packages/pygazebo-3.0.0_2014.1-py2.7.egg

**Comment by RDaneelOlivav** [comment]
Tried in Gazebo2.2.1 and Gazebo 5.1.

**Comment by jpieper** [comment]
Are you using the example from "master" or "develop".  There was a slight fix to the example since the most recent release required to make it work.  I believe the correct example should be (which I just tested and seems to work).  I believe the major difference was that the old example forgot to set the "name" field.

```import trollius
from trollius import From

import pygazebo
import pygazebo.msg.joint_cmd_pb2

@trollius.coroutine
def publish_loop():
    manager = yield From(pygazebo.connect())

```
publisher = yield From(
    manager.advertise('/gazebo/default/model/joint_cmd',
                      'gazebo.msgs.JointCmd'))

message = pygazebo.msg.joint_cmd_pb2.JointCmd()
message.name = 'robot::joint_name'
message.axis = 0
message.force = 1.0

while True:
    yield From(publisher.publish(message))
    yield From(trollius.sleep(1.0))
```

loop = trollius.get_event_loop()
loop.run_until_complete(publish_loop())

```
```

**Comment by RDaneelOlivav** [comment]
Let me try right now ;)

**Comment by RDaneelOlivav** [comment]
Worked like a charm ;). Thanks ;). You wouldnt know by any chance how to save a world of gazebo useing useing these topics? I know it should be written in the topics of requests with the tag sdf_world I think. Any idea of how that could be accomplished? Thanks again ;)

**Comment by RDaneelOlivav** [comment]
And a question reffered to this message.name, it can be any name I suppose?

**Comment by RDaneelOlivav** [comment]
Worked like a charm ;)
